### ISSUE TITLE
Implement pagination to posts and pages GET endpoints

### ISSUE THREAD

**Issue by markjamesm** [markjamesm/Sprocket#5]
Need to add pagination to:

- GET /api/pages/
- GET /api/posts

**Comment by Amir-Helali** [comment]
Hi @markjamesm. I submitted a PR that addresses the functionality required for this issue. Feel free to reach out after reviewing if any changes are needed.

**Comment by markjamesm** [comment]
Thanks @Amir-Helali! I just had two small changes which I've added in the comments. Once you make the changes I'll approve the PR.

**Comment by Amir-Helali** [comment]
@markjamesm Done
